# Generated by Django 5.2.3 on 2025-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='web_port',
            field=models.PositiveIntegerField(default=80, help_text='Порт веб-интерфейса (обычно 80 или 443)'),
        ),
    ]
