# Generated by Django 5.2.3 on 2025-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_web_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_login_checked',
            field=models.DateTimeField(blank=True, help_text='Время последней проверки авторизации', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_login_status',
            field=models.BooleanField(blank=True, help_text='Статус последней проверки авторизации', null=True),
        ),
    ]
