# Generated by Django 5.2.3 on 2025-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_last_login_checked_device_last_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='file_path',
            field=models.FileField(max_length=255, upload_to='docs/'),
        ),
    ]
