# Generated by Django 5.2.3 on 2025-07-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_documentation_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='methodology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
