# Generated by Django 5.2.3 on 2025-07-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_feature_methodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, unique=True)),
                ('methodology', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='methodology',
        ),
    ]
