# Generated by Django 5.2.3 on 2025-07-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_featuremethodology_remove_feature_methodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSupportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'Поддерживается'), ('no', 'Не поддерживается'), ('unknown', 'Неизвестно')], default='unknown', max_length=10)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_status', to='devices.feature')),
            ],
        ),
    ]
