DEFAULT_FEATURES = [
    "Реализация IP версии 4",
    "Реализация ARP",
    "Реализация VLAN",
    "Реализация протокола создания VLAN",
    "Реализация протокола стекирования VLAN",
    "Реализация ICMP",
    "ICMP тип 0,8 (ping)",
    "ICMP тип 3 (адресат недоступен)",
    "ICMP тип 11 (trace route)",
    "Реализация DHCP для IPv4",
    "DHCP Relay",
    "Поддержка DHCP snooping",
    "Поддержка DHCP anti-spoofing",
    "DHCP-сервер",
    "DHCP-клиент",
    "Реализация RIP",
    "Реализация IGMP",
    "IGMP Proxy",
    "IGMP Snooping",
    "IGMP Fast leave",
    "Поддержка IGMP v.3. Совместимость V3 c V2",
    "Реализация UDP",
    "Реализация TCP",
]
